version: '3.9'
services:
  mongodb:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongodb

volumes:
  mongodb: {}
