version: '3.9'
services:
  frontend: 
    container_name: frontapp
    build: ./frontend
    ports: 
      - "80:80"
    depends_on:
      - database
    networks:
      - mynet
  
  backend:
    container_name: server
    build: ./backend
    ports: 
      - "3500:3500"
    environment:
      - host=mysql
      - user=root
      - password=mysql123
      - database=school
    depends_on:
      - database
    networks:
      - mynet
  
  database:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    networks:
      - mynet
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
networks:
  mynet:
    driver: bridge
    
