version: '3'
services:
  frontend: 
    container_name: frontend
    build: 
      context: frontend/
    image: fronted-image
    ports: 
      - "80:80"
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: backend/
    image: backend-image
    ports: 
      - "3500:3500"
    environment:
      - host=db
      - user=root
      - password=rootpassword
      - database=exampledb

    depends_on:
      - db
  db:
    container_name: mysql-container
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
